export enum ParameterTypeEnum {
  PRICE_PER_KM = 0,
  MIN_INSPECTION_PICTURES,
  MAX_INSPECTION_PICTURES,
  RETRY_DISTRIBUTION_TIME,
  CHECK_FOR_LOCATION_UPDATE_TIME,
  MAX_DISTRIBUTION_RETRY_TIMES,
  CHECK_TACTICAL_RESPONSE_TIME,
  MAX_DISTANCE,
  DISTANCE_INCREASE_RATIO,
  MAX_INCREASED_DISTANCE,
  MAX_DISTANCE_CHECKIN
}